// ReportGrid Visualization


/**
* PivotTable 
*
* Useage:  ReportGrid.pivotTable("tableParentId", path, { rows : impression.carrier, columns : impressions.network });
*
* Generates a pivot table representing an intersection of the supplied event values and path, appending the table to the HTML element with the supplied Id.
*/

$estr=function(){return js.Boot.__string_rec(this,"")};typeof js=="undefined"&&(js={});js.Boot=function(){};js.Boot.__name__=["js","Boot"];js.Boot.__unhtml=function(a){return a.split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;")};js.Boot.__trace=function(a,b){var c=b!=null?b.fileName+":"+b.lineNumber+": ":"";c+=js.Boot.__unhtml(js.Boot.__string_rec(a,""))+"<br/>";var e=document.getElementById("haxe:trace");e==null?alert("No haxe:trace element defined\n"+c):e.innerHTML+=c};
js.Boot.__clear_trace=function(){var a=document.getElementById("haxe:trace");if(a!=null)a.innerHTML=""};js.Boot.__closure=function(a,b){var c=a[b];if(c==null)return null;var e=function(){return c.apply(a,arguments)};e.scope=a;e.method=c;return e};
js.Boot.__string_rec=function(a,b){if(a==null)return"null";if(b.length>=5)return"<...>";var c=typeof a;if(c=="function"&&(a.__name__!=null||a.__ename__!=null))c="object";switch(c){case "object":if(a instanceof Array){if(a.__enum__!=null){if(a.length==2)return a[0];c=a[0]+"(";b+="\t";for(var e=2,f=a.length;e<f;){var g=e++;c+=g!=2?","+js.Boot.__string_rec(a[g],b):js.Boot.__string_rec(a[g],b)}return c+")"}e=a.length;c="[";b+="\t";for(f=0;f<e;)g=f++,c+=(g>0?",":"")+js.Boot.__string_rec(a[g],b);c+="]";
return c}try{f=a.toString}catch(h){return"???"}if(f!=null&&f!=Object.toString&&(c=a.toString(),c!="[object Object]"))return c;f=null;c="{\n";b+="\t";e=a.hasOwnProperty!=null;for(f in a)if(!e||a.hasOwnProperty(f))f=="prototype"||f=="__class__"||f=="__super__"||f=="__interfaces__"||(c.length!=2&&(c+=", \n"),c+=b+f+" : "+js.Boot.__string_rec(a[f],b));b=b.substring(1);c+="\n"+b+"}";return c;case "function":return"<function>";case "string":return a;default:return String(a)}};
js.Boot.__interfLoop=function(a,b){if(a==null)return!1;if(a==b)return!0;var c=a.__interfaces__;if(c!=null)for(var e=0,f=c.length;e<f;){var g=e++,g=c[g];if(g==b||js.Boot.__interfLoop(g,b))return!0}return js.Boot.__interfLoop(a.__super__,b)};
js.Boot.__instanceof=function(a,b){try{if(a instanceof b){if(b==Array)return a.__enum__==null;return!0}if(js.Boot.__interfLoop(a.__class__,b))return!0}catch(c){if(b==null)return!1}switch(b){case Int:return Math.ceil(a%2147483648)===a;case Float:return typeof a=="number";case Bool:return a===!0||a===!1;case String:return typeof a=="string";case Dynamic:return!0;default:if(a==null)return!1;return a.__enum__==b||b==Class&&a.__name__!=null||b==Enum&&a.__ename__!=null}};
js.Boot.__init=function(){js.Lib.isIE=typeof document!="undefined"&&document.all!=null&&typeof window!="undefined"&&window.opera==null;js.Lib.isOpera=typeof window!="undefined"&&window.opera!=null;Array.prototype.copy=Array.prototype.slice;Array.prototype.insert=function(a,c){this.splice(a,0,c)};Array.prototype.remove=Array.prototype.indexOf?function(a){a=this.indexOf(a);if(a==-1)return!1;this.splice(a,1);return!0}:function(a){for(var c=0,e=this.length;c<e;){if(this[c]==a)return this.splice(c,1),
!0;c++}return!1};Array.prototype.iterator=function(){return{cur:0,arr:this,hasNext:function(){return this.cur<this.arr.length},next:function(){return this.arr[this.cur++]}}};if(String.prototype.cca==null)String.prototype.cca=String.prototype.charCodeAt;String.prototype.charCodeAt=function(a){a=this.cca(a);if(a!=a)return null;return a};var a=String.prototype.substr;String.prototype.substr=function(b,c){if(b!=null&&b!=0&&c!=null&&c<0)return"";if(c==null)c=this.length;b<0?(b=this.length+b,b<0&&(b=0)):
c<0&&(c=this.length+c-b);return a.apply(this,[b,c])};$closure=js.Boot.__closure};js.Boot.prototype.__class__=js.Boot;typeof dom=="undefined"&&(dom={});dom.HTMLElementExtensions=function(){};dom.HTMLElementExtensions.__name__=["dom","HTMLElementExtensions"];dom.HTMLElementExtensions.getStyle=function(a,b){return $closure(dom.Env.window,"getComputedStyle")!=null?dom.Env.window.getComputedStyle(a,null).getPropertyValue(b):a.currentStyle!=null?a.currentStyle[b]:""};
dom.HTMLElementExtensions.append=function(a,b){a.appendChild(b);return a};dom.HTMLElementExtensions.withStyle=function(a,b,c){a.style[b]=c;return a};dom.HTMLElementExtensions.html=function(a,b){a.innerHTML=b;return a};dom.HTMLElementExtensions.prototype.__class__=dom.HTMLElementExtensions;js.Lib=function(){};js.Lib.__name__=["js","Lib"];js.Lib.isIE=null;js.Lib.isOpera=null;js.Lib.document=null;js.Lib.window=null;js.Lib.alert=function(a){alert(js.Boot.__string_rec(a,""))};js.Lib.eval=function(a){return eval(a)};
js.Lib.setErrorHandler=function(a){js.Lib.onerror=a};js.Lib.prototype.__class__=js.Lib;dom.DOMTokenList=function(){};dom.DOMTokenList.__name__=["dom","DOMTokenList"];dom.DOMTokenList.prototype.length=null;dom.DOMTokenList.prototype.item=null;dom.DOMTokenList.prototype.contains=null;dom.DOMTokenList.prototype.add=null;dom.DOMTokenList.prototype.remove=null;dom.DOMTokenList.prototype.toggle=null;dom.DOMTokenList.prototype.stringifier=null;dom.DOMTokenList.prototype.__class__=dom.DOMTokenList;
dom.DOMSettableTokenList=function(){};dom.DOMSettableTokenList.__name__=["dom","DOMSettableTokenList"];dom.DOMSettableTokenList.prototype.value=null;dom.DOMSettableTokenList.prototype.length=null;dom.DOMSettableTokenList.prototype.item=null;dom.DOMSettableTokenList.prototype.contains=null;dom.DOMSettableTokenList.prototype.add=null;dom.DOMSettableTokenList.prototype.remove=null;dom.DOMSettableTokenList.prototype.toggle=null;dom.DOMSettableTokenList.prototype.stringifier=null;
dom.DOMSettableTokenList.prototype.__class__=dom.DOMSettableTokenList;dom.DOMStringList=function(){};dom.DOMStringList.__name__=["dom","DOMStringList"];dom.DOMStringList.prototype.item=null;dom.DOMStringList.prototype.contains=null;dom.DOMStringList.prototype.length=null;dom.DOMStringList.prototype.__class__=dom.DOMStringList;dom.NameList=function(){};dom.NameList.__name__=["dom","NameList"];dom.NameList.prototype.getName=null;dom.NameList.prototype.getNamespaceURI=null;
dom.NameList.prototype.contains=null;dom.NameList.prototype.containsNS=null;dom.NameList.prototype.length=null;dom.NameList.prototype.__class__=dom.NameList;dom.NamedNodeMap=function(){};dom.NamedNodeMap.__name__=["dom","NamedNodeMap"];dom.NamedNodeMap.prototype.getNamedItem=null;dom.NamedNodeMap.prototype.setNamedItem=null;dom.NamedNodeMap.prototype.removeNamedItem=null;dom.NamedNodeMap.prototype.item=null;dom.NamedNodeMap.prototype.getNamedItemNS=null;dom.NamedNodeMap.prototype.setNamedItemNS=null;
dom.NamedNodeMap.prototype.removeNamedItemNS=null;dom.NamedNodeMap.prototype.length=null;dom.NamedNodeMap.prototype.__class__=dom.NamedNodeMap;dom.TimedTrackCueList=function(){};dom.TimedTrackCueList.__name__=["dom","TimedTrackCueList"];dom.TimedTrackCueList.prototype.length=null;dom.TimedTrackCueList.prototype.getter=null;dom.TimedTrackCueList.prototype.getCueById=null;dom.TimedTrackCueList.prototype.__class__=dom.TimedTrackCueList;dom.Selection=function(){};dom.Selection.__name__=["dom","Selection"];
dom.Selection.prototype.anchorNode=null;dom.Selection.prototype.anchorOffset=null;dom.Selection.prototype.focusNode=null;dom.Selection.prototype.focusOffset=null;dom.Selection.prototype.isCollapsed=null;dom.Selection.prototype.rangeCount=null;dom.Selection.prototype.collapse=null;dom.Selection.prototype.collapseToStart=null;dom.Selection.prototype.collapseToEnd=null;dom.Selection.prototype.selectAllChildren=null;dom.Selection.prototype.deleteFromDocument=null;dom.Selection.prototype.getRangeAt=null;
dom.Selection.prototype.addRange=null;dom.Selection.prototype.removeRange=null;dom.Selection.prototype.removeAllRanges=null;dom.Selection.prototype.stringifier=null;dom.Selection.prototype.__class__=dom.Selection;dom.MessagePortArray=function(){};dom.MessagePortArray.__name__=["dom","MessagePortArray"];dom.MessagePortArray.prototype.__class__=dom.MessagePortArray;dom.MessagePort=function(){};dom.MessagePort.__name__=["dom","MessagePort"];dom.MessagePort.prototype.postMessage=null;
dom.MessagePort.prototype.start=null;dom.MessagePort.prototype.close=null;dom.MessagePort.prototype.onMessage=null;dom.MessagePort.prototype.__class__=dom.MessagePort;dom.MediaList=function(){};dom.MediaList.__name__=["dom","MediaList"];dom.MediaList.prototype.mediaText=null;dom.MediaList.prototype.length=null;dom.MediaList.prototype.item=null;dom.MediaList.prototype.deleteMedium=null;dom.MediaList.prototype.appendMedium=null;dom.MediaList.prototype.__class__=dom.MediaList;
dom.Double=function(a,b){if(a!==$_)this._1=a,this._2=b};dom.Double.__name__=["dom","Double"];dom.Double.prototype._1=null;dom.Double.prototype._2=null;dom.Double.prototype.__class__=dom.Double;typeof pivotTable=="undefined"&&(pivotTable={});pivotTable.AbstractPivotTable=function(a){if(a!==$_)this._rg=ReportGrid,this._fail=function(a){dom.Console.warning("Default Failure Called "+a)}};pivotTable.AbstractPivotTable.__name__=["pivotTable","AbstractPivotTable"];
pivotTable.AbstractPivotTable.prototype._rg=null;pivotTable.AbstractPivotTable.prototype._fail=null;pivotTable.AbstractPivotTable.prototype.giveSearchResultsTo=function(a,b,c){var e={where:{}};Lambda.iter(b,function(a){e.where[a._1]=a._2});this._rg.searchCount(a,e,c,this._fail)};pivotTable.AbstractPivotTable.prototype.giveValuesTo=function(a,b,c){this._rg.fieldValues(a,{field:b},c)};
pivotTable.AbstractPivotTable.prototype.giveCountTo=function(a,b,c,e){this._rg.fieldValueCount(a,{field:b,value:c},e)};pivotTable.AbstractPivotTable.prototype.givePathChildrenTo=function(a,b,c){var e={type:"path"};c!=null&&(e.field=c);this._rg.children(a,e,function(c){b(a,c)},this._fail)};pivotTable.AbstractPivotTable.prototype.giveAllChildrenTo=function(a,b,c){var e={type:"all"};b!=null&&(e.field=b);this._rg.children(a,e,function(a){c(a)},this._fail)};
pivotTable.AbstractPivotTable.prototype.givePropertyChildrenTo=function(a,b,c){var e={type:"field"};b!=null&&(e.field=b);this._rg.children(a,e,function(a){c(a)},this._fail)};pivotTable.AbstractPivotTable.prototype.__class__=pivotTable.AbstractPivotTable;
pivotTable.PivotTableFactory=function(a,b,c){if(a!==$_)pivotTable.AbstractPivotTable.call(this),this._path=b,this._rows={reportGrid:!0},this._cols={reportGrid:!0},this._rowPath=c.rows,this._colPath=c.columns,this._table=dom.HTMLDocumentExtensions.getId(dom.Env.document,a),this._config=c,this._colsReady=this._rowsReady=!1,this.setupTable()};pivotTable.PivotTableFactory.__name__=["pivotTable","PivotTableFactory"];pivotTable.PivotTableFactory.__super__=pivotTable.AbstractPivotTable;
for(var k in pivotTable.AbstractPivotTable.prototype)pivotTable.PivotTableFactory.prototype[k]=pivotTable.AbstractPivotTable.prototype[k];pivotTable.PivotTableFactory.prototype._path=null;pivotTable.PivotTableFactory.prototype._rowPath=null;pivotTable.PivotTableFactory.prototype._colPath=null;pivotTable.PivotTableFactory.prototype._rows=null;pivotTable.PivotTableFactory.prototype._cols=null;pivotTable.PivotTableFactory.prototype._table=null;pivotTable.PivotTableFactory.prototype._config=null;
pivotTable.PivotTableFactory.prototype._rowsReady=null;pivotTable.PivotTableFactory.prototype._colsReady=null;pivotTable.PivotTableFactory.prototype.setupTable=function(){var a=this;this.setTableNames(this._rows,this._path,this._rowPath,function(){a._rowsReady=!0;a.buildTable()});this.setTableNames(this._cols,this._path,this._colPath,function(){a._colsReady=!0;a.buildTable()})};pivotTable.PivotTableFactory.prototype.setTableNames=function(a,b,c,e){this.giveValuesTo(b,c,function(b){a[c]=b;e()})};
pivotTable.PivotTableFactory.prototype.buildTable=function(){this._rowsReady&&this._colsReady&&new pivotTable.PivotTable(this._table,Reflect.field(this._rows,this._rowPath),Reflect.field(this._cols,this._colPath),this._path,this._config)};pivotTable.PivotTableFactory.prototype.__class__=pivotTable.PivotTableFactory;
pivotTable.PivotTable=function(a,b,c,e,f){if(a!==$_)pivotTable.AbstractPivotTable.call(this),this._doc=dom.Env.document,this._parent=a,this._config=f,this._rows=b,this._cols=c,this._tr=[],this._td=[],this._index="pivot-index-"+Std.string(Math.round(Math.random()*99999))+"-",this._path=e,this._eventId=this.toLabelText(f.rows.substr(0,f.rows.lastIndexOf("."))),this._rowId=this.toLabelText(StringTools.replace(f.rows,this._eventId,"")),this._colId=this.toLabelText(StringTools.replace(f.columns,this._eventId,
"")),this.createTable()};pivotTable.PivotTable.__name__=["pivotTable","PivotTable"];pivotTable.PivotTable.__super__=pivotTable.AbstractPivotTable;for(k in pivotTable.AbstractPivotTable.prototype)pivotTable.PivotTable.prototype[k]=pivotTable.AbstractPivotTable.prototype[k];pivotTable.PivotTable.prototype._doc=null;pivotTable.PivotTable.prototype._config=null;pivotTable.PivotTable.prototype._parent=null;pivotTable.PivotTable.prototype._pivotTable=null;pivotTable.PivotTable.prototype._rows=null;
pivotTable.PivotTable.prototype._cols=null;pivotTable.PivotTable.prototype._tr=null;pivotTable.PivotTable.prototype._td=null;pivotTable.PivotTable.prototype._index=null;pivotTable.PivotTable.prototype._path=null;pivotTable.PivotTable.prototype._eventId=null;pivotTable.PivotTable.prototype._rowId=null;pivotTable.PivotTable.prototype._colId=null;
pivotTable.PivotTable.prototype.createTable=function(){this._pivotTable=dom.HTMLDocumentExtensions.newElement(this._doc,"table",[new dom.Double("id",this._index+"master"),new dom.Double("width","auto"),new dom.Double("frame","border"),new dom.Double("cellspacing","0"),new dom.Double("border","1"),new dom.Double("cellpadding","3")],"width: auto; text-align: center; px; height: auto; border-style: solid; padding: 1px;");this._parent.appendChild(this.createHeaderTable());dom.HTMLDocumentExtensions.getId(this._doc,
this._index+"container").appendChild(this._pivotTable);this.createRows()};
pivotTable.PivotTable.prototype.createHeaderTable=function(){var a=dom.HTMLDocumentExtensions.newElement(this._doc,"table",[new dom.Double("id",this._index+"headers"),new dom.Double("border","1"),new dom.Double("cellpadding","1"),new dom.Double("cellspacing","0"),new dom.Double("frame","border")],"position: relative; width: auto; height: auto;");dom.HTMLElementExtensions.append(dom.HTMLElementExtensions.append(a,dom.HTMLElementExtensions.append(dom.HTMLElementExtensions.append(this.newHeaderRow(),dom.HTMLElementExtensions.append(this.newHeaderColumn(),
this.newLabel(this._eventId))),dom.HTMLElementExtensions.append(this.newHeaderColumn(),this.newLabel(this._colId)))),dom.HTMLElementExtensions.withStyle(dom.HTMLElementExtensions.append(dom.HTMLElementExtensions.append(this.newHeaderRow(),dom.HTMLElementExtensions.append(this.newHeaderColumn(),this.newLabel(this._rowId))),this.newColumn([new dom.Double("id",this._index+"container")])),"textAlign","left"));return a};
pivotTable.PivotTable.prototype.createRows=function(){this.addLabelSpaceToArrays();for(var a=0,b=this._rows.length;a<b;){var c=a++,c=this.newRow([new dom.Double(this._index+"row",Std.string(c))]);this._tr.push(c);this._pivotTable.appendChild(c)}this.createColumns()};
pivotTable.PivotTable.prototype.createColumns=function(){for(var a=0,b=this._cols.length;a<b;)for(var c=a++,e=0,f=this._tr.length;e<f;){var g=e++,h=this.newColumn([new dom.Double("id",this.toIndex(c,g)),new dom.Double("width",100/this._cols.length+"%")]);this._td.push(h);this._tr[g].appendChild(h)}this.fillTableValues()};pivotTable.PivotTable.prototype.addLabelSpaceToArrays=function(){this._cols.unshift(" ");this._rows.unshift(" ")};
pivotTable.PivotTable.prototype.fillTableValues=function(){this.applyLabels();this.applyCounts()};pivotTable.PivotTable.prototype.applyLabels=function(){for(var a=0,b=this._cols.length;a<b;){var c=a++;this.setLabelElement(c,0,this._cols[c])}a=0;for(b=this._rows.length;a<b;)c=a++,this.setLabelElement(0,c,this._rows[c])};
pivotTable.PivotTable.prototype.applyCounts=function(){for(var a=this,b=1,c=this._cols.length;b<c;)for(var e=[b++],f=1,g=this._rows.length;f<g;){var h=[f++];this.giveSearchResultsTo(this._path,[new dom.Double(this._config.rows,this._rows[h[0]]),new dom.Double(this._config.columns,this._cols[e[0]])],function(b,c){return function(e){a.setIndex(c[0],b[0],Std.string(e))}}(h,e))}};pivotTable.PivotTable.prototype.newRow=function(a){return dom.HTMLDocumentExtensions.newElement(this._doc,"tr",a,"width: 100%; height: auto; text-align: center;")};
pivotTable.PivotTable.prototype.newHeaderColumn=function(){return dom.HTMLDocumentExtensions.newElement(this._doc,"td",[new dom.Double("class","pivot-table-header")],"width: auto; height: auto; text-align: center;")};pivotTable.PivotTable.prototype.newHeaderRow=function(){return dom.HTMLDocumentExtensions.newElement(this._doc,"tr",[new dom.Double("class","pivot-table-header")],"width: auto; height: auto; text-align: center;")};
pivotTable.PivotTable.prototype.newColumn=function(a){return dom.HTMLDocumentExtensions.newElement(this._doc,"td",a,"width: auto; height: auto;")};pivotTable.PivotTable.prototype.newLabel=function(a){return dom.HTMLElementExtensions.html(dom.HTMLDocumentExtensions.newElement(this._doc,"span",[new dom.Double("class","pivot-table-label")],"font-weight: bold;"),a)};
pivotTable.PivotTable.prototype.newTableContent=function(a){return dom.HTMLElementExtensions.html(dom.HTMLDocumentExtensions.newElement(this._doc,"span",[new dom.Double("class","pivot-table-content")],"width: 100%; text-align: center"),a)};pivotTable.PivotTable.prototype.setLabelElement=function(a,b,c){return dom.HTMLElementExtensions.withStyle(dom.HTMLElementExtensions.append(this.getIndex(a,b),this.newLabel(c)),"backgroundColor","#b5dfff")};
pivotTable.PivotTable.prototype.toIndex=function(a,b){return this._index+Std.string(a)+"x"+Std.string(b)};pivotTable.PivotTable.prototype.getIndex=function(a,b){return dom.HTMLDocumentExtensions.getId(this._doc,this.toIndex(a,b))};pivotTable.PivotTable.prototype.setIndex=function(a,b,c){return dom.HTMLElementExtensions.append(this.getIndex(a,b),this.newTableContent(c))};pivotTable.PivotTable.prototype.toLabelText=function(a){return a.charAt(0)=="."?StringTools.replace(a,".",""):a};
pivotTable.PivotTable.prototype.__class__=pivotTable.PivotTable;Std=function(){};Std.__name__=["Std"];Std.is=function(a,b){return js.Boot.__instanceof(a,b)};Std.string=function(a){return js.Boot.__string_rec(a,"")};Std["int"]=function(a){if(a<0)return Math.ceil(a);return Math.floor(a)};Std.parseInt=function(a){var b=parseInt(a,10);b==0&&a.charCodeAt(1)==120&&(b=parseInt(a));if(isNaN(b))return null;return b};Std.parseFloat=function(a){return parseFloat(a)};
Std.random=function(a){return Math.floor(Math.random()*a)};Std.prototype.__class__=Std;Lambda=function(){};Lambda.__name__=["Lambda"];Lambda.array=function(a){for(var b=[],a=a.iterator();a.hasNext();){var c=a.next();b.push(c)}return b};Lambda.list=function(a){for(var b=new List,a=a.iterator();a.hasNext();){var c=a.next();b.add(c)}return b};Lambda.map=function(a,b){for(var c=new List,e=a.iterator();e.hasNext();){var f=e.next();c.add(b(f))}return c};
Lambda.mapi=function(a,b){for(var c=new List,e=0,f=a.iterator();f.hasNext();){var g=f.next();c.add(b(e++,g))}return c};Lambda.has=function(a,b,c){if(c==null)for(c=a.iterator();c.hasNext();){if(a=c.next(),a==b)return!0}else for(var e=a.iterator();e.hasNext();)if(a=e.next(),c(a,b))return!0;return!1};Lambda.exists=function(a,b){for(var c=a.iterator();c.hasNext();){var e=c.next();if(b(e))return!0}return!1};Lambda.foreach=function(a,b){for(var c=a.iterator();c.hasNext();){var e=c.next();if(!b(e))return!1}return!0};
Lambda.iter=function(a,b){for(var c=a.iterator();c.hasNext();){var e=c.next();b(e)}};Lambda.filter=function(a,b){for(var c=new List,e=a.iterator();e.hasNext();){var f=e.next();b(f)&&c.add(f)}return c};Lambda.fold=function(a,b,c){for(a=a.iterator();a.hasNext();)var e=a.next(),c=b(e,c);return c};Lambda.count=function(a,b){var c=0;if(b==null)for(var e=a.iterator();e.hasNext();)e.next(),c++;else for(e=a.iterator();e.hasNext();){var f=e.next();b(f)&&c++}return c};Lambda.empty=function(a){return!a.iterator().hasNext()};
Lambda.indexOf=function(a,b){for(var c=0,e=a.iterator();e.hasNext();){var f=e.next();if(b==f)return c;c++}return-1};Lambda.concat=function(a,b){for(var c=new List,e=a.iterator();e.hasNext();){var f=e.next();c.add(f)}for(e=b.iterator();e.hasNext();)f=e.next(),c.add(f);return c};Lambda.prototype.__class__=Lambda;dom.Console=function(){};dom.Console.__name__=["dom","Console"];dom.Console.log=function(a){dom.Console.logger.log(a)};dom.Console.debug=function(a){dom.Console.logger.debug(a)};
dom.Console.info=function(a){dom.Console.logger.info(a)};dom.Console.warning=function(a){dom.Console.logger.warn(a)};dom.Console.error=function(a){dom.Console.logger.error(a)};dom.Console.prototype.__class__=dom.Console;dom.Env=function(){};dom.Env.__name__=["dom","Env"];dom.Env.eq=function(a,b){return a===b};dom.Env.alert=function(a){alert(Std.string(a))};dom.Env.decodeURI=function(a){return decodeURI(a)};dom.Env.decodeURIComponent=function(a){return decodeURIComponent(a)};dom.Env.encodeURI=function(a){return encodeURI(a)};
dom.Env.encodeURIComponent=function(a){return encodeURIComponent(a)};dom.Env.escape=function(a){return escape(a)};dom.Env.unescape=function(a){return unescape(a)};dom.Env.eval=function(a){return eval(a)};dom.Env.isFinite=function(a){return isFinite(a)};dom.Env.isNaN=function(a){return isNaN(a)};dom.Env.isDefined=function(a){return dom.Env.typeOf(a)!="undefined"};dom.Env.isDefinedGlobal=function(a){return typeof window[a]!="undefined"};dom.Env.typeOf=function(a){return typeof a};
dom.Env.getElementsByClass=function(a,b,c){return function(a,b,c){getElementsByClassName=document.getElementsByClassName?function(a,b,c){for(var a=(c||document).getElementsByClassName(a),b=b?RegExp("\u0008"+b+"\u0008","i"):null,c=[],e,f=0,g=a.length;f<g;f+=1)e=a[f],(!b||b.test(e.nodeName))&&c.push(e);return c}:document.evaluate?function(a,b,c){for(var b=b||"*",c=c||document,e=a.split(" "),f="",g=document.documentElement.namespaceURI==="http://www.w3.org/1999/xhtml"?"http://www.w3.org/1999/xhtml":
null,a=[],j,i=0,e=e.length;i<e;i+=1)f+="[contains(concat(space, @class, space), (space + classes[j] + space))]";try{j=document.evaluate(".//"+b+f,c,g,0,null)}catch(l){j=document.evaluate(".//"+b+f,c,null,0,null)}for(;b=j.iterateNext();)a.push(b);return a}:document.getElementsByTagName("*")?function(a,b,c){for(var e=[],b=(c||document).getElementsByTagName(b||"*"),c=0;c<b.length;c++)RegExp(a,"i").test(b[c].className)&&e.push(b[c]);return e}:function(a,b,c){var b=b||"*",c=c||document,e=a.split(" "),
a=[],b=b==="*"&&c.all?c.all:c.getElementsByTagName(b),c=[],f;f=0;for(var g=e.length;f<g;f+=1)a.push(RegExp("(^|s)"+e[f]+"(s|$)"));for(var g=0,j=b.length;g<j;g+=1){e=b[g];f=!1;for(var i=0,l=a.length;i<l;i+=1)if(f=a[i].test(e.className),!f)break;f&&c.push(e)}return c};return getElementsByClassName(a,b,c)}(a,b,c)};
dom.Env.setCookie=function(a,b,c,e,f,g){Date.now();a=dom.Env.asCookiePair(a,b,!1)+dom.Env.getCookieExpiration(c)+dom.Env.asCookiePair("path",e,!0,"/")+dom.Env.asCookiePair("domain",f,!0)+(g==!0?"secure":"");dom.Env.document.cookie=a};dom.Env.getCookie=function(a){for(var b=dom.Env.getCookies(),c=null,e=0,f=b.length;e<f;){var g=e++;StringTools.startsWith(b[g],a)&&(c=b[g].split("=")[1])}return c};dom.Env.getCookies=function(){return dom.Env.document.cookie.split(";")};
dom.Env.getCookieExpiration=function(a){return a!=null?function(){var b=Date.fromTime(Date.now().getTime()+a*864E5);return";expires="+Std.string(b.toGMTString())}(this):""};dom.Env.asCookiePair=function(a,b,c,e){c==null&&(c=!0);c=c?";":"";return b!=null?c+a+"="+b:e!=null?c+a+"="+e:""};dom.Env.prototype.__class__=dom.Env;dom.XmlHttpRequestState=function(){};dom.XmlHttpRequestState.__name__=["dom","XmlHttpRequestState"];dom.XmlHttpRequestState.prototype.__class__=dom.XmlHttpRequestState;
dom.ExceptionCode=function(){};dom.ExceptionCode.__name__=["dom","ExceptionCode"];dom.ExceptionCode.prototype.__class__=dom.ExceptionCode;dom.NodeType=function(){};dom.NodeType.__name__=["dom","NodeType"];dom.NodeType.prototype.__class__=dom.NodeType;dom.DocumentPosition=function(){};dom.DocumentPosition.__name__=["dom","DocumentPosition"];dom.DocumentPosition.prototype.__class__=dom.DocumentPosition;dom.DerivationMethod=function(){};dom.DerivationMethod.__name__=["dom","DerivationMethod"];
dom.DerivationMethod.prototype.__class__=dom.DerivationMethod;dom.OperationType=function(){};dom.OperationType.__name__=["dom","OperationType"];dom.OperationType.prototype.__class__=dom.OperationType;dom.ErrorState=function(){};dom.ErrorState.__name__=["dom","ErrorState"];dom.ErrorState.prototype.__class__=dom.ErrorState;dom.ReadyState=function(){};dom.ReadyState.__name__=["dom","ReadyState"];dom.ReadyState.prototype.__class__=dom.ReadyState;dom.EventExceptionCode=function(){};
dom.EventExceptionCode.__name__=["dom","EventExceptionCode"];dom.EventExceptionCode.prototype.__class__=dom.EventExceptionCode;dom.DeltaModeCode=function(){};dom.DeltaModeCode.__name__=["dom","DeltaModeCode"];dom.DeltaModeCode.prototype.__class__=dom.DeltaModeCode;dom.InputModeCode=function(){};dom.InputModeCode.__name__=["dom","InputModeCode"];dom.InputModeCode.prototype.__class__=dom.InputModeCode;dom.KeyLocationCode=function(){};dom.KeyLocationCode.__name__=["dom","KeyLocationCode"];
dom.KeyLocationCode.prototype.__class__=dom.KeyLocationCode;dom.PhaseType=function(){};dom.PhaseType.__name__=["dom","PhaseType"];dom.PhaseType.prototype.__class__=dom.PhaseType;dom.AttrChangeType=function(){};dom.AttrChangeType.__name__=["dom","AttrChangeType"];dom.AttrChangeType.prototype.__class__=dom.AttrChangeType;dom.AcceptNodeConstants=function(){};dom.AcceptNodeConstants.__name__=["dom","AcceptNodeConstants"];dom.AcceptNodeConstants.prototype.__class__=dom.AcceptNodeConstants;
dom.WhatToShowConstants=function(){};dom.WhatToShowConstants.__name__=["dom","WhatToShowConstants"];dom.WhatToShowConstants.prototype.__class__=dom.WhatToShowConstants;dom.RangeExceptionCode=function(){};dom.RangeExceptionCode.__name__=["dom","RangeExceptionCode"];dom.RangeExceptionCode.prototype.__class__=dom.RangeExceptionCode;dom.CompareHow=function(){};dom.CompareHow.__name__=["dom","CompareHow"];dom.CompareHow.prototype.__class__=dom.CompareHow;dom.RuleType=function(){};
dom.RuleType.__name__=["dom","RuleType"];dom.RuleType.prototype.__class__=dom.RuleType;dom.CSSValueType=function(){};dom.CSSValueType.__name__=["dom","CSSValueType"];dom.CSSValueType.prototype.__class__=dom.CSSValueType;dom.PrimitiveType=function(){};dom.PrimitiveType.__name__=["dom","PrimitiveType"];dom.PrimitiveType.prototype.__class__=dom.PrimitiveType;dom.UpdateStatus=function(){};dom.UpdateStatus.__name__=["dom","UpdateStatus"];dom.UpdateStatus.prototype.__class__=dom.UpdateStatus;
dom.ErrorSeverity=function(){};dom.ErrorSeverity.__name__=["dom","ErrorSeverity"];dom.ErrorSeverity.prototype.__class__=dom.ErrorSeverity;StringTools=function(){};StringTools.__name__=["StringTools"];StringTools.urlEncode=function(a){return encodeURIComponent(a)};StringTools.urlDecode=function(a){return decodeURIComponent(a.split("+").join(" "))};StringTools.htmlEscape=function(a){return a.split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;")};StringTools.htmlUnescape=function(a){return a.split("&gt;").join(">").split("&lt;").join("<").split("&amp;").join("&")};
StringTools.startsWith=function(a,b){return a.length>=b.length&&a.substr(0,b.length)==b};StringTools.endsWith=function(a,b){var c=b.length,e=a.length;return e>=c&&a.substr(e-c,c)==b};StringTools.isSpace=function(a,b){var c=a.charCodeAt(b);return c>=9&&c<=13||c==32};StringTools.ltrim=function(a){for(var b=a.length,c=0;c<b&&StringTools.isSpace(a,c);)c++;return c>0?a.substr(c,b-c):a};
StringTools.rtrim=function(a){for(var b=a.length,c=0;c<b&&StringTools.isSpace(a,b-c-1);)c++;return c>0?a.substr(0,b-c):a};StringTools.trim=function(a){return StringTools.ltrim(StringTools.rtrim(a))};StringTools.rpad=function(a,b,c){for(var e=a.length,f=b.length;e<c;)c-e<f?(a+=b.substr(0,c-e),e=c):(a+=b,e+=f);return a};StringTools.lpad=function(a,b,c){var e="",f=a.length;if(f>=c)return a;for(var g=b.length;f<c;)c-f<g?(e+=b.substr(0,c-f),f=c):(e+=b,f+=g);return e+a};
StringTools.replace=function(a,b,c){return a.split(b).join(c)};StringTools.hex=function(a,b){var c="";do c="0123456789ABCDEF".charAt(a&15)+c,a>>>=4;while(a>0);if(b!=null)for(;c.length<b;)c="0"+c;return c};StringTools.fastCodeAt=function(a,b){return a.cca(b)};StringTools.isEOF=function(a){return a!=a};StringTools.prototype.__class__=StringTools;List=function(a){if(a!==$_)this.length=0};List.__name__=["List"];List.prototype.h=null;List.prototype.q=null;List.prototype.length=null;
List.prototype.add=function(a){a=[a];this.h==null?this.h=a:this.q[1]=a;this.q=a;this.length++};List.prototype.push=function(a){this.h=a=[a,this.h];if(this.q==null)this.q=a;this.length++};List.prototype.first=function(){return this.h==null?null:this.h[0]};List.prototype.last=function(){return this.q==null?null:this.q[0]};List.prototype.pop=function(){if(this.h==null)return null;var a=this.h[0];this.h=this.h[1];if(this.h==null)this.q=null;this.length--;return a};
List.prototype.isEmpty=function(){return this.h==null};List.prototype.clear=function(){this.q=this.h=null;this.length=0};List.prototype.remove=function(a){for(var b=null,c=this.h;c!=null;){if(c[0]==a){b==null?this.h=c[1]:b[1]=c[1];if(this.q==c)this.q=b;this.length--;return!0}b=c;c=c[1]}return!1};List.prototype.iterator=function(){return{h:this.h,hasNext:function(){return this.h!=null},next:function(){if(this.h==null)return null;var a=this.h[0];this.h=this.h[1];return a}}};
List.prototype.toString=function(){var a=new StringBuf,b=!0,c=this.h;for(a.b[a.b.length]="{";c!=null;)b?b=!1:a.b[a.b.length]=", ",a.b[a.b.length]=Std.string(c[0]),c=c[1];a.b[a.b.length]="}";return a.b.join("")};List.prototype.join=function(a){for(var b=new StringBuf,c=!0,e=this.h;e!=null;)c?c=!1:b.b[b.b.length]=a,b.b[b.b.length]=e[0],e=e[1];return b.b.join("")};List.prototype.filter=function(a){for(var b=new List,c=this.h;c!=null;){var e=c[0],c=c[1];a(e)&&b.add(e)}return b};
List.prototype.map=function(a){for(var b=new List,c=this.h;c!=null;){var e=c[0],c=c[1];b.add(a(e))}return b};List.prototype.__class__=List;Reflect=function(){};Reflect.__name__=["Reflect"];Reflect.hasField=function(a,b){if(a.hasOwnProperty!=null)return a.hasOwnProperty(b);for(var c=Reflect.fields(a).iterator();c.hasNext();)if(c.next()==b)return!0;return!1};Reflect.field=function(a,b){var c=null;try{c=a[b]}catch(e){}return c};Reflect.setField=function(a,b,c){a[b]=c};
Reflect.callMethod=function(a,b,c){return b.apply(a,c)};Reflect.fields=function(a){if(a==null)return[];var b=[];if(a.hasOwnProperty)for(var c in a)a.hasOwnProperty(c)&&b.push(c);else{var e;try{e=a.__proto__}catch(f){e=null}if(e!=null)a.__proto__=null;for(c in a)c!="__proto__"&&b.push(c);if(e!=null)a.__proto__=e}return b};Reflect.isFunction=function(a){return typeof a=="function"&&a.__name__==null};Reflect.compare=function(a,b){return a==b?0:a>b?1:-1};
Reflect.compareMethods=function(a,b){if(a==b)return!0;if(!Reflect.isFunction(a)||!Reflect.isFunction(b))return!1;return a.scope==b.scope&&a.method==b.method&&a.method!=null};Reflect.isObject=function(a){if(a==null)return!1;var b=typeof a;return b=="string"||b=="object"&&!a.__enum__||b=="function"&&a.__name__!=null};Reflect.deleteField=function(a,b){if(!Reflect.hasField(a,b))return!1;delete a[b];return!0};
Reflect.copy=function(a){for(var b={},c=0,e=Reflect.fields(a);c<e.length;){var f=e[c];++c;b[f]=Reflect.field(a,f)}return b};Reflect.makeVarArgs=function(a){return function(){for(var b=[],c=0,e=arguments.length;c<e;){var f=c++;b.push(arguments[f])}return a(b)}};Reflect.prototype.__class__=Reflect;StringBuf=function(a){if(a!==$_)this.b=[]};StringBuf.__name__=["StringBuf"];StringBuf.prototype.add=function(a){this.b[this.b.length]=a};
StringBuf.prototype.addSub=function(a,b,c){this.b[this.b.length]=a.substr(b,c)};StringBuf.prototype.addChar=function(a){this.b[this.b.length]=String.fromCharCode(a)};StringBuf.prototype.toString=function(){return this.b.join("")};StringBuf.prototype.b=null;StringBuf.prototype.__class__=StringBuf;pivotTable.Main=function(){};pivotTable.Main.__name__=["pivotTable","Main"];pivotTable.Main.main=function(){var a=ReportGrid;if(a!=null)a.pivotTable=pivotTable.PivotTableFactory};
pivotTable.Main.prototype.__class__=pivotTable.Main;dom.HTMLEventExtensions=function(){};dom.HTMLEventExtensions.__name__=["dom","HTMLEventExtensions"];dom.HTMLEventExtensions.cancelBubbling=function(a){a.cancelBubble!=null?a.cancelBubble=!0:a.stopPropagation()};dom.HTMLEventExtensions.getRelatedTarget=function(a){var b=a.toElement,a=a.relatedTarget;return b!=null?b:a!=null?a:null};dom.HTMLEventExtensions.prototype.__class__=dom.HTMLEventExtensions;
IntIter=function(a,b){if(a!==$_)this.min=a,this.max=b};IntIter.__name__=["IntIter"];IntIter.prototype.min=null;IntIter.prototype.max=null;IntIter.prototype.hasNext=function(){return this.min<this.max};IntIter.prototype.next=function(){return this.min++};IntIter.prototype.__class__=IntIter;dom.HTMLDocumentExtensions=function(){};dom.HTMLDocumentExtensions.__name__=["dom","HTMLDocumentExtensions"];
dom.HTMLDocumentExtensions.newElement=function(a,b,c,e){e==null&&(e="");for(var a=a.createElement(b),b=0,f=c.length;b<f;){var g=b++;a.setAttribute(c[g]._1,c[g]._2)}a.style.cssText=e;return a};dom.HTMLDocumentExtensions.getId=function(a,b){return a.getElementById(b)};dom.HTMLDocumentExtensions.getIds=function(a,b){for(var c=[],e=0,f=b.length;e<f;){var g=e++;c.push(dom.HTMLDocumentExtensions.getId(a,b[g]))}return c};dom.HTMLDocumentExtensions.getTags=function(a,b){return a.getElementsByTagName(b)};
dom.HTMLDocumentExtensions.getClasses=function(a,b){return dom.Env.getElementsByClass(b)};dom.HTMLDocumentExtensions.prototype.__class__=dom.HTMLDocumentExtensions;$_={};js.Boot.__res={};js.Boot.__init();js.Lib.document=document;js.Lib.window=window;onerror=function(a,b,c){var e=js.Lib.onerror;if(e==null)return!1;return e(a,[b+":"+c])};var d=Date;d.now=function(){return new Date};d.fromTime=function(a){var b=new Date;b.setTime(a);return b};
d.fromString=function(a){switch(a.length){case 8:var a=a.split(":"),b=new Date;b.setTime(0);b.setUTCHours(a[0]);b.setUTCMinutes(a[1]);b.setUTCSeconds(a[2]);return b;case 10:return a=a.split("-"),new Date(a[0],a[1]-1,a[2],0,0,0);case 19:return a=a.split(" "),b=a[0].split("-"),a=a[1].split(":"),new Date(b[0],b[1]-1,b[2],a[0],a[1],a[2]);default:throw"Invalid date format : "+a;}};
d.prototype.toString=function(){var a=this.getMonth()+1,b=this.getDate(),c=this.getHours(),e=this.getMinutes(),f=this.getSeconds();return this.getFullYear()+"-"+(a<10?"0"+a:""+a)+"-"+(b<10?"0"+b:""+b)+" "+(c<10?"0"+c:""+c)+":"+(e<10?"0"+e:""+e)+":"+(f<10?"0"+f:""+f)};d.prototype.__class__=d;d.__name__=["Date"];String.prototype.__class__=String;String.__name__=["String"];Array.prototype.__class__=Array;Array.__name__=["Array"];Int={__name__:["Int"]};Dynamic={__name__:["Dynamic"]};Float=Number;
Float.__name__=["Float"];Bool={__ename__:["Bool"]};Class={__name__:["Class"]};Enum={};Void={__ename__:["Void"]};Math.__name__=["Math"];Math.NaN=Number.NaN;Math.NEGATIVE_INFINITY=Number.NEGATIVE_INFINITY;Math.POSITIVE_INFINITY=Number.POSITIVE_INFINITY;Math.isFinite=function(a){return isFinite(a)};Math.isNaN=function(a){return isNaN(a)};js.Lib.onerror=null;dom.Console.logger=console;dom.Env.document=document;dom.Env.documentRaw=document;dom.Env.screen=screen;dom.Env.window=window;
dom.Env.navigator=navigator;dom.Env.history=history;dom.Env.JInfinity=Infinity;dom.Env.JNaN=NaN;dom.Env.JUndefined=void 0;dom.XmlHttpRequestState.UNSENT=0;dom.XmlHttpRequestState.OPENED=1;dom.XmlHttpRequestState.HEADERS_RECEIVED=2;dom.XmlHttpRequestState.LOADING=3;dom.XmlHttpRequestState.DONE=4;dom.ExceptionCode.INDEX_SIZE_ERR=1;dom.ExceptionCode.DOMSTRING_SIZE_ERR=2;dom.ExceptionCode.HIERARCHY_REQUEST_ERR=3;dom.ExceptionCode.WRONG_DOCUMENT_ERR=4;dom.ExceptionCode.INVALID_CHARACTER_ERR=5;
dom.ExceptionCode.NO_DATA_ALLOWED_ERR=6;dom.ExceptionCode.NO_MODIFICATION_ALLOWED_ERR=7;dom.ExceptionCode.NOT_FOUND_ERR=8;dom.ExceptionCode.NOT_SUPPORTED_ERR=9;dom.ExceptionCode.INUSE_ATTRIBUTE_ERR=10;dom.ExceptionCode.INVALID_STATE_ERR=11;dom.ExceptionCode.SYNTAX_ERR=12;dom.ExceptionCode.INVALID_MODIFICATION_ERR=13;dom.ExceptionCode.NAMESPACE_ERR=14;dom.ExceptionCode.INVALID_ACCESS_ERR=15;dom.ExceptionCode.VALIDATION_ERR=16;dom.ExceptionCode.TYPE_MISMATCH_ERR=17;dom.NodeType.ELEMENT_NODE=1;
dom.NodeType.ATTRIBUTE_NODE=2;dom.NodeType.TEXT_NODE=3;dom.NodeType.CDATA_SECTION_NODE=4;dom.NodeType.ENTITY_REFERENCE_NODE=5;dom.NodeType.ENTITY_NODE=6;dom.NodeType.PROCESSING_INSTRUCTION_NODE=7;dom.NodeType.COMMENT_NODE=8;dom.NodeType.DOCUMENT_NODE=9;dom.NodeType.DOCUMENT_TYPE_NODE=10;dom.NodeType.DOCUMENT_FRAGMENT_NODE=11;dom.NodeType.NOTATION_NODE=12;dom.DocumentPosition.DOCUMENT_POSITION_DISCONNECTED=1;dom.DocumentPosition.DOCUMENT_POSITION_PRECEDING=2;
dom.DocumentPosition.DOCUMENT_POSITION_FOLLOWING=4;dom.DocumentPosition.DOCUMENT_POSITION_CONTAINS=8;dom.DocumentPosition.DOCUMENT_POSITION_CONTAINED_BY=16;dom.DocumentPosition.DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC=32;dom.DerivationMethod.DERIVATION_RESTRICTION=1;dom.DerivationMethod.DERIVATION_EXTENSION=2;dom.DerivationMethod.DERIVATION_UNION=4;dom.DerivationMethod.DERIVATION_LIST=8;dom.OperationType.NODE_CLONED=1;dom.OperationType.NODE_IMPORTED=2;dom.OperationType.NODE_DELETED=3;
dom.OperationType.NODE_RENAMED=4;dom.OperationType.NODE_ADOPTED=5;dom.ErrorState.NETWORK_EMPTY=0;dom.ErrorState.NETWORK_IDLE=1;dom.ErrorState.NETWORK_LOADING=2;dom.ErrorState.NETWORK_NO_SOURCE=3;dom.ReadyState.CONNECTING=0;dom.ReadyState.OPEN=1;dom.ReadyState.CLOSED=2;dom.EventExceptionCode.UNSPECIFIED_EVENT_TYPE_ERR=0;dom.DeltaModeCode.DOM_DELTA_PIXEL=0;dom.DeltaModeCode.DOM_DELTA_Line=1;dom.DeltaModeCode.DOM_DELTA_Page=2;dom.InputModeCode.DOM_INPUT_METHOD_UNKNOWN=0;
dom.InputModeCode.DOM_INPUT_METHOD_KEYBOARD=1;dom.InputModeCode.DOM_INPUT_METHOD_PASTE=2;dom.InputModeCode.DOM_INPUT_METHOD_DROP=3;dom.InputModeCode.DOM_INPUT_METHOD_IME=4;dom.InputModeCode.DOM_INPUT_METHOD_OPTION=5;dom.InputModeCode.DOM_INPUT_METHOD_HANDWRITING=6;dom.InputModeCode.DOM_INPUT_METHOD_VOICE=7;dom.InputModeCode.DOM_INPUT_METHOD_MULTIMODAL=8;dom.InputModeCode.DOM_INPUT_METHOD_SCRIPT=9;dom.KeyLocationCode.DOM_KEY_LOCATION_STANDARD=0;dom.KeyLocationCode.DOM_KEY_LOCATION_LEFT=1;
dom.KeyLocationCode.DOM_KEY_LOCATION_RIGHT=2;dom.KeyLocationCode.DOM_KEY_LOCATION_NUMPAD=3;dom.KeyLocationCode.DOM_KEY_LOCATION_MOBILE=4;dom.KeyLocationCode.DOM_KEY_LOCATION_JOYSTICK=5;dom.PhaseType.CAPTURING_PHASE=1;dom.PhaseType.AT_TARGET=2;dom.PhaseType.BUBBLING_PHASE=3;dom.AttrChangeType.MODIFICATION=1;dom.AttrChangeType.ADDITION=2;dom.AttrChangeType.REMOVAL=3;dom.AcceptNodeConstants.FILTER_ACCEPT=1;dom.AcceptNodeConstants.FILTER_REJECT=2;dom.AcceptNodeConstants.FILTER_SKIP=1;
dom.WhatToShowConstants.SHOW_ALL=-1;dom.WhatToShowConstants.SHOW_ELEMENT=1;dom.WhatToShowConstants.SHOW_ATTRIBUTE=2;dom.WhatToShowConstants.SHOW_TEXT=4;dom.WhatToShowConstants.SHOW_CDATA_SECTION=8;dom.WhatToShowConstants.SHOW_ENTITY_REFERENCE=16;dom.WhatToShowConstants.SHOW_ENTITY=32;dom.WhatToShowConstants.SHOW_PROCESSING_INSTRUCTION=64;dom.WhatToShowConstants.SHOW_COMMENT=128;dom.WhatToShowConstants.SHOW_DOCUMENT=256;dom.WhatToShowConstants.SHOW_DOCUMENT_TYPE=512;
dom.WhatToShowConstants.SHOW_DOCUMENT_FRAGMENT=1024;dom.WhatToShowConstants.SHOW_NOTATION=2048;dom.RangeExceptionCode.BAD_BOUNDARYPOINTS_ERR=1;dom.RangeExceptionCode.INVALID_NODE_TYPE_ERR=2;dom.CompareHow.START_TO_START=0;dom.CompareHow.START_TO_END=1;dom.CompareHow.END_TO_END=2;dom.CompareHow.END_TO_START=3;dom.RuleType.UNKNOWN_RULE=0;dom.RuleType.STYLE_RULE=1;dom.RuleType.CHARSET_RULE=2;dom.RuleType.IMPORT_RULE=3;dom.RuleType.MEDIA_RULE=4;dom.RuleType.FONT_FACE_RULE=5;dom.RuleType.PAGE_RULE=6;
dom.CSSValueType.CSS_INHERIT=0;dom.CSSValueType.CSS_PRIMITIVE_VALUE=1;dom.CSSValueType.CSS_VALUE_LIST=2;dom.CSSValueType.CSS_CUSTOM=3;dom.PrimitiveType.CSS_UNKNOWN=0;dom.PrimitiveType.CSS_NUMBER=1;dom.PrimitiveType.CSS_PERCENTAGE=2;dom.PrimitiveType.CSS_EMS=3;dom.PrimitiveType.CSS_EXS=4;dom.PrimitiveType.CSS_PX=5;dom.PrimitiveType.CSS_CM=6;dom.PrimitiveType.CSS_MM=7;dom.PrimitiveType.CSS_IN=8;dom.PrimitiveType.CSS_PT=9;dom.PrimitiveType.CSS_PC=10;dom.PrimitiveType.CSS_DEG=11;
dom.PrimitiveType.CSS_RAD=12;dom.PrimitiveType.CSS_GRAD=13;dom.PrimitiveType.CSS_MS=14;dom.PrimitiveType.CSS_S=15;dom.PrimitiveType.CSS_HZ=16;dom.PrimitiveType.CSS_KHZ=17;dom.PrimitiveType.CSS_DIMENSION=18;dom.PrimitiveType.CSS_STRING=19;dom.PrimitiveType.CSS_URI=20;dom.PrimitiveType.CSS_IDENT=21;dom.PrimitiveType.CSS_ATTR=22;dom.PrimitiveType.CSS_COUNTER=23;dom.PrimitiveType.CSS_RECT=24;dom.PrimitiveType.CSS_RGBCOLOR=25;dom.UpdateStatus.UNCACHED=0;dom.UpdateStatus.IDLE=1;
dom.UpdateStatus.CHECKING=2;dom.UpdateStatus.DOWNLOADING=3;dom.UpdateStatus.UPDATEREADY=4;dom.ErrorSeverity.SEVERITY_WARNING=1;dom.ErrorSeverity.SEVERITY_ERROR=2;dom.ErrorSeverity.SEVERITY_FATAL_ERROR=3;pivotTable.Main.main();